### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by MargaretaKusan** [theleftbit/BSWInterfaceKit#22]
Hey! I think you got something wrong with the function pinToSuperviewSafeLayoutEdges, you have constraints set like this:

```
safeAreaLayoutGuide.leadingAnchor.constraint(equalTo: superView.leadingAnchor, constant: margin.left)
```
here you pin the safeAreaLayoutGuide of the subview to the superview’s leadingAnchor (without safeAreaLayoutGuide)

i think it should be other way around

subView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor)

for example if i activate constraints this way, it works for me, while using the pinToSuperviewSafeLayoutEdges doesn’t

**Comment by piercifani** [comment]
Can you please check if [this](https://github.com/BlurredSoftware/BSWInterfaceKit/commit/e39d2db414bb3065ff9b7d8da1eae81a9117228a) fixes it?
